apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: pg
  template:
    metadata:
      labels:
        component: pg
    spec:
      volumes:
        - name: pg-storage
          persistentVolumeClaim:
            claimName: db-persistent-volume-claim
      containers:
        - name: pg
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-storage
              subPath: postgres
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD